COMPILE=g++ "./projects/magic banana/src/main.cc" -lglut -lGL -lX11 -ldl -lxml2 -o "./projects/magic banana/src/magic banana"
all:
	$(COMPILE) 
run:
	$(COMPILE); "././projects/magic banana/src/magic banana"
clean:
	rm "././projects/magic banana/src/magic banana"
