COMPILE=g++ "./projects/Test Project/src/main.cc" -lglut -lGL -lX11 -ldl -lxml2 -o "./projects/Test Project/src/Test Project"
all:
	$(COMPILE) 
run:
	$(COMPILE); "././projects/Test Project/src/Test Project"
clean:
	rm "././projects/Test Project/src/Test Project"
